name = "CharFuncPricing"
uuid = "1fb851c3-be98-478b-9657-166436d5cfc1"
authors = ["Jherek Healy <jherekhealy@protonmail.com>"]
version = "0.2.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DoubleExponentialFormulas = "eb426421-6452-4132-80ef-4b100a757ac5"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
julia = "1"

[extras]
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TaylorSeries = "6aa5eb33-94cf-58f4-a9d0-e4b2c4fc25ea"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Nemo", "TaylorSeries", "StatsBase"]
